name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: development

    steps:
      - run: sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true

      - run: bundle exec rspec --format RSpec::Github::Formatter
